### ISSUE TITLE
ReactJs Implementation

### ISSUE THREAD

**Issue by omalave** [Klemen1337/browser-thermal-printer#3]
Hello!

I was trying to implement this library in reactjs and I cannot get It working, do you have any example using reactjs?

```
import ThermalPrinter, { PrinterTypes, TableAlign } from "../src/core"

async function printTest() {

  const printer = new ThermalPrinter();
  printer.print("Hello World"); // Append text
  printer.println("Hello World"); // Append text with new line
}

module.exports = {
  printTest: printTest
};
```

I know that doesn't work because '../src/core' but if I try with 

`const ThermalPrinter = require('browser-thermal-printer');`

It doesn't works. I got this error: TypeError: ThermalPrinter is not a constructor

Any help?

**Comment by Klemen1337** [comment]
Hi 👋 Have you solved your issue? 

This code would work:

```javascript
import ThermalPrinter, { PrinterTypes, TableAlign } from "browser-thermal-printer"

export async function printTest() {
  const printer = new ThermalPrinter();
  printer.print("Hello World"); // Append text
  printer.println("Hello World"); // Append text with new line
}
```
