### ISSUE TITLE
Printer connection question

### ISSUE THREAD

**Issue by carlosa54** [Klemen1337/browser-thermal-printer#4]
Hi @Klemen1337 thanks for this module.

I have a question on how to ultimately send the commands to the printer.
From the code I see that you accumulate a Buffer with all the commands but how do you connect to the printer and send the buffer from the browser?

I see the [Tested printers](https://github.com/Klemen1337/browser-thermal-printer#tested-printers) section in the README. Can you provide an example on what you're using to send the buffer commands to the printer?

**Comment by Klemen1337** [comment]
Hi 👋 
This library was not intended to interface with printers. It simply creates the buffer with commands that you can send to the printer with other methods or libraries. In the future I have plans to add TCP and Serial connections.
A good example to print with serial is https://github.com/jaedson-barbosa/browser-thermal-printer-encoder/blob/master/src/PrinterManager.ts. 
And TCP connection can be established with WebSockets
```javascript
var connection = new WebSocket('wss://ip:port');
connection.binaryType = 'arraybuffer';
connection.onopen = function () {
  connection.send(buffer);
};
```

**Comment by huydinhle** [comment]
@Klemen1337 I tried the code you put here. I ran into this error.  Can you give me some pointer to fix this error?
```
./node_modules/browser-thermal-printer/src/core.ts
Module parse failed: Unexpected token (8:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| // import unorm from "unorm";
| 
> export enum PrinterTypes {
|   "EPSON" = "epson",
|   "STAR" = "star"
```
